os:
    - linux
language: php

php:
  - '7.2'

dist: xenial

jobs:
    include:
        #melakukan testing
        - stage: "Tests"
        - name: "Unit Test PHP"
        - script:
            - travis_retry composer self-update
            - travis_retry composer install --prefer-source --no-interaction
            - cp .env.example .env
            - php artisan key:generate
            - vendor/bin.phpunit
        #melakukan build images dan publish ke docker hub
        - stage: "Build Docker Image"
          name: "Build Images Docker"
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password
            - docker build -t travis-ci-build-stages-demo $DOCKER_USERNAME/cicd-laravel
            - docker push $DOCKER_USERNAME/cicd-laravel